[slackware] Improve slackbuilds command

diff --git a/bin/bin/myslack b/bin/bin/myslack
--- a/bin/bin/myslack
+++ b/bin/bin/myslack
@@ -3,16 +3,19 @@
 # See https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash#13359121
 # for bash parameter handling
 
-set -e
+#set -eo pipefail
 
 SLACKBUILDS_DIR="/opt/slackbuilds"
 ACTION="install"
 CONFIRMATION="n"
 PACKAGE="$1"
+SKIP_DEPENDENCIES=""
 SKIP_MD5_CHECK=""
 SUDO=""
+VERBOSE=0
 
 GREEN='\033[0;32m'
+MAGENTA='\033[0;35m'
 RED='\033[0;31m'
 RESET='\033[0m'
 YELLOW='\033[0;33m'
@@ -24,23 +27,52 @@ log() {
     local lvl="${2:-INFO}"
     local color="$RESET"
 
+    [[ "$lvl" = "DEBUG" && $VERBOSE -ne 1 ]] && return
+
+    [[ "$lvl" = "DEBUG" ]] && color="$MAGENTA"
     [[ "$lvl" = "INFO" ]] && color="$GREEN"
     [[ "$lvl" = "WARN" ]] && color="$YELLOW"
     [[ "$lvl" = "ERROR" ]] && color="$RED"
 
-    echo -e "[${color}${lvl}${RESET}] $1"
+    echo -e "[${color}${lvl}${RESET}] $1" 1>&2
+}
+
+# Check if package is already installed
+#
+# @return 0 if package is installed
+# @return 2 if package is not installed
+is_sb_installed () {
+    local current_version="$(find /var/log/packages/ -name "${1}-*")"
+
+    log "is_sb_installed: pkg=$1, version='$current_version'" "DEBUG"
+    if [ -n "$current_version" ]; then
+        return 0
+    fi
+
+    return 1
 }
 
 function install_dependencies() {
     local dependencies="$1"
     local action="${2:-install}"
+    local confirmatin="${3:-n}"
+    local result=
 
+    log "==== Installing dependencies: $dependencies"
     for dep in $dependencies; do
         packages=$(find $SLACKBUILDS_DIR -type d -name "$dep")
-        log "Installing dependency... $dependencies -- $packages"
+        log "===== Installing dependency... $dep -- $packages"
 
         for pkg_path in $packages; do
-            install_sb "$pkg_path" $action
+            install_sb "$pkg_path" "$action" "$confirmation"
+            result=$?
+
+            log "install_dependencies: $dep ($pkg_path), result = $result" "DEBUG"
+            if [ $result -eq 0 ]; then
+                log "======== Installed $pkg_path"
+            elif [ $result -eq 1 ]; then
+                log "$dep already installed"
+            fi
         done
     done
 }
@@ -48,29 +80,59 @@ function install_dependencies() {
 function install_sb() {
     local path="$1"
     local action="${2:-install}"
+    local confirmation="${3:-n}"
+    local build_result=
+    local pkg_name=
+    local is_installed=
+    PRGNAM=""
+    VERSION=""
+    DOWNLOAD=""
+    MD5SUM=""
+    DOWNLOAD_x86_64=""
+    MD5SUM_x86_64=""
+    REQUIRES=""
 
     if [ -z "$path" ]; then
         log "Invalid slackbuild: '$path'" "ERROR"
         return
     fi
 
-    pushd $path
-    local pkg_name="$(basename $path)"
+    # read package information
+    source "$path/$(basename $path).info"
+    pkg_name="$PRGNAM-$VERSION"
 
-    if [ $(is_sb_installed $pkg_name) -eq 0 -a $action = "install" ]; then
-        log "$pkg_name already installed, skipping..." "WARN"
-        popd
-        return
+    if [ "$confirmation" = 'n' ]; then
+        local msg="Package: $PRGNAM ($VERSION)"
+        if [ -n "$REQUIRES" ]; then
+            msg="$msg\n  Dependencies:\n"
+            msg="$msg$(tr ' ' '\n' <<< $REQUIRES | xargs printf "    * %s\n")"
+        fi
+        log "$msg"
+        read -p "[PROMPT] Go ahead with $action? [y/N]:" confirmation
     fi
 
-    # read package information
-    source $PWD/$pkg_name.info
+    log "$PRGNAM: confirmation = $confirmation ($pkg_name, $path)" "DEBUG"
+    if [ "$confirmation" != 'y' ]; then
+        exit 0
+    fi
 
-    if [ -n "$REQUIRES" ]; then
-        install_dependencies $REQUIRES $action
+    log "=== Installing $pkg_name ($path)"
+
+    is_sb_installed $pkg_name
+    is_installed=$?
+    if [ $action = "install" -a $is_installed -eq 0 ]; then
+        log "$pkg_name already installed, skipping..." "WARN"
+        popd 1>/dev/null
+        return 1
+    fi
+
+    if [ -n "$REQUIRES" -a "$SKIP_DEPENDENCIES" != "y" ]; then
+        install_dependencies "$REQUIRES" "$action" $confirmation
     fi
 
     log "Installing $path..."
+    pushd "$path"
+    source "$path/$(basename "$path").info"
     # check if DOWNLOAD_x86_64 is configured
     if [ "$DOWNLOAD" == "UNSUPPORTED" -a -n "$DOWNLOAD_x86_64" ]; then
         DOWNLOAD="$DOWNLOAD_x86_64"
@@ -97,17 +159,31 @@ function install_sb() {
 
     if [ -n "$MD5SUM" -a "$SKIP_MD5_CHECK" != "y" ]; then
         log "Comparing MD5 checksum..." "WARN"
-        if [ "$MD5SUM" != "$(md5sum "$(basename "$DOWNLOAD")" | cut -d' ' -f 1)" ]; then
-            log "MD5SUM does not match, exiting..." "ERROR"
+        ACTUAL_MD5SUM="$(md5sum "$(basename "$DOWNLOAD")" | cut -d' ' -f 1)"
+        MD5_FOUND=1
+
+        for MD5 in $MD5SUM; do
+            log "Comparing MD5 sum: MD5 = $MD5" "DEBUG"
+            [ "$MD5" == "$ACTUAL_MD5SUM" ] && MD5_FOUND=0
+        done
+
+        if [ $MD5_FOUND -ne 0 ]; then
+            log "MD5SUM does not match; expected $ACTUAL_MD5SUM, got $MD5SUM. Exiting..." "ERROR"
             exit 1
         fi
     fi
 
     log "Running slack build script"
     notify-send "Slackbuild" "Running build script for $pkg_name. May need password"
-    $SUDO sh "$PWD/${pkg_name}.SlackBuild"
+    $SUDO sh "$PWD/${PRGNAM}.SlackBuild"
+    build_result=$?
 
-    log "Installing package"
+    if [ $build_result -ne 0 ]; then
+        log "Error running $PRGNAM.SlackBuild" "ERROR"
+        exit 1
+    fi
+
+    log "Installing package $pkg_name"
     notify-send "Slackbuild" "Installing $pkg_name. May need password"
     $SUDO /sbin/upgradepkg --install-new /tmp/${PRGNAM}-*.tgz
 
@@ -115,22 +191,9 @@ function install_sb() {
         log "Failed to install $path" "ERROR"
     fi
 
-    rm "$(echo $DOWNLOAD | tr '/' '\n' | tail -n 1)"
-    popd
-}
-
-# Check if package is already installed
-#
-# @return 0 if package is installed
-# @return 2 if package is not installed
-function is_sb_installed() {
-    local current_version="$(find /var/log/packages/ -name "${1}-*")"
-
-    if [ -n "$current_version" ]; then
-        echo 0
-    else
-        echo 2
-    fi
+    rm "$(tr '/' '\n' <<< $DOWNLOAD | tail -n 1)"
+    popd 1>/dev/null
+    return 0
 }
 
 function print_help() {
@@ -148,6 +211,11 @@ ACTIONS
   [i]nstall     Install package
   [d]esc        Show package description (slack-desc), if found.
   [s]earch      Show package description (slack-desc), if found.
+
+OPTIONS
+
+  -v|--verbose  Be verbose
+  -s|--skip-dependencies  Skip dependencies installation
 EOS
 }
 
@@ -181,8 +249,16 @@ while [[ $# -gt 0 ]]; do
             CONFIRMATION="y"
             shift
             ;;
+        -s|--skip-dependencies)
+            SKIP_DEPENDENCIES="y"
+            shift
+            ;;
         --skip-md5)
             SKIP_MD5_CHECK="y"
+            shift
+            ;;
+        -v|--verbose)
+            VERBOSE=1
             shift
             ;;
         -h|--help)
@@ -206,13 +282,7 @@ if [ $ACTION = "info" -o $ACTION = "install" -o $ACTION = "upgrade" ]; then
             echo "$pkg =================================================== $pkg_path"
             cat $pkg_path/$pkg.info
         else
-            if [ "$CONFIRMATION" = 'n' ]; then
-                read -p "[PROMPT] Install $pkg_path ? [y/N]:" CONFIRMATION
-            fi
-
-            if [ "$CONFIRMATION" = 'y' ]; then
-                install_sb "$pkg_path" $ACTION
-            fi
+            install_sb "$pkg_path" $ACTION "$CONFIRMATION"
         fi
     done
 
